easy_admin:
    site_name: Планировщик посадки растений Plantify
    edit:
        title: 'Редактировать'
    new:
        title: 'Добавить'

    design:
        menu:
            - { route: 'user_index', label: 'На главную', icon: 'home' }
            - { entity: 'Plant', label: 'Растения', icon: 'tree' }
            - { entity: 'Planting', label: 'Посадка', icon: 'comments' }
            - { entity: 'Region', label: 'Регион', icon: 'map-marker' }

    entities:
        Plant:
            class: App\Entity\Plant
            label: 'Растения'
            list:
                title: 'Растения'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'plantings', label: 'Посадка' }
                    - { property: 'follower', label: 'Потом сажать' }
                    - { property: 'companion', label: 'Можно комбинировать с' }
            new:
                title: 'Добавить'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'plantings', label: 'Посадка' }
                    - { property: 'follower', label: 'Потом сажать' }
                    - { property: 'companion', label: 'Можно комбинировать с' }
            edit:
                title: 'Редактировать'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'description', label: 'Описание' }
                    - { property: 'plantings', label: 'Посадка' }
                    - { property: 'follower', label: 'Потом сажать' }
                    - { property: 'companion', label: 'Можно комбинировать с' }
        Planting:
            class: App\Entity\Planting
            label: 'Посадки'
            list:
                title: 'Посадки'
                fields:
                    - { property: 'plantingMonth', label: 'Месяц посадки' }
                    - { property: 'plant', label: 'Растение' }
                    - { property: 'region', label: 'Регион' }
            new:
                title: 'Добавить'
                fields:
                    - { property: 'plantingMonth', label: 'Месяц посадки' }
                    - { property: 'plant', label: 'Растение' }
                    - { property: 'region', label: 'Регион' }
            edit:
                title: 'Редактировать'
                fields:
                    - { property: 'plantingMonth', label: 'Месяц посадки' }
                    - { property: 'plant', label: 'Растение' }
                    - { property: 'region', label: 'Регион' }

        Region:
            class: App\Entity\Region
            label: 'Регион'
            list:
                title: 'Регион'
                fields:
                    - { property: 'name', label: 'Регион' }
            new:
                title: 'Добавить'
                fields:
                    - { property: 'name', label: 'Регион' }
            edit:
                title: 'Редактировать'
                fields:
                    - { property: 'name', label: 'Регион' }
