# admin
admin_index:
    path: /admin_old
    controller: App\Controller\AdminController::index

admin_add_plants:
    path: /admin_old/plants/add
    controller: App\Controller\AdminController::addPlants

admin_list_plants:
    path: /admin_old/plants/list
    controller: App\Controller\AdminController::getListPlants


