garden_index:
    path: /garden
    controller: App\Controller\GardenController::index

garden_create:
    path: /garden/create
    controller: App\Controller\GardenController::create

garden_delete:
    path: /garden/delete
    controller: App\Controller\GardenController::delete
