garden_index:
    path: /garden
    controller: App\Controller\GardenController::index

garden_create:
    path: /garden/create
    controller: App\Controller\GardenController::create

assign_plant_to_cell:
    path: /garden/cell/{cellId}/plant/{plantId}
    controller: App\Controller\GardenController::assignPlantToCell
    methods: PUT

garden_delete:
    path: /garden/delete
    controller: App\Controller\GardenController::delete
    methods: POST
