history_month:
    path: /history/{year}
    controller: App\Controller\HistoryController::index
    methods: GET

history_index:
    path: /history
    controller: App\Controller\HistoryController::index
    methods: GET
