todo_index:
    path: /todo
    controller: App\Controller\TodoController::index
    methods: GET

todo_mark_as_done:
    path: /todo/{planningId}/mark-done
    controller: App\Controller\TodoController::markAsDone
    methods: PUT
