# admin
admin_index:
    path: /admin
    controller: App\Controller\AdminController::index

admin_add_plants:
    path: /admin/plants/add
    controller: App\Controller\AdminController::addPlants

# user
user_index:
    path: /
    controller: App\Controller\UserController::index

